(() => {
  const canvas = document.querySelector('#game');
  const ctx = canvas.getContext('2d');
  const W = 480, H = 720, groundY = 662;
  const DIFFICULTIES = {
    chill: { label: 'CHILL', speed: 135, maxSpeed: 190, gap: 215, spacing: 330, color: '#72e6c5' },
    classic: { label: 'CLASSIC', speed: 165, maxSpeed: 240, gap: 182, spacing: 290, color: '#ffe46e' },
    turbo: { label: 'TURBO', speed: 205, maxSpeed: 290, gap: 155, spacing: 255, color: '#ff8e9f' }
  };
  const state = { mode: 'menu', difficulty: 'classic', score: 0, best: +(localStorage.skyboundBest || 0), stars: 0, time: 0, speed: 165, muted: false };
  const bird = { x: 126, y: 330, vy: 0, r: 18, rot: 0 };
  let gates = [], particles = [], clouds = [], last = performance.now(), audio;
  for (let i=0;i<8;i++) clouds.push({x:Math.random()*W,y:70+Math.random()*400,s:25+Math.random()*50,v:5+Math.random()*10});
  function tone(freq=440,duration=.07,type='sine',volume=.035){if(state.muted)return;audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
  function reset(){const d=DIFFICULTIES[state.difficulty];state.score=0;state.stars=0;state.speed=d.speed;bird.y=330;bird.vy=0;gates=[];particles=[];addGate(W+150);addGate(W+150+d.spacing)}
  function start(difficulty=state.difficulty){state.difficulty=difficulty;if(state.mode==='gameover'||state.mode==='menu')reset();state.mode='playing';flap()}
  function flap(){if(state.mode!=='playing')return;bird.vy=-345;tone(520,.06,'triangle');for(let i=0;i<5;i++)particles.push({x:bird.x-16,y:bird.y+(Math.random()-.5)*12,vx:-70-Math.random()*60,vy:(Math.random()-.5)*60,life:.45,c:'#fff'})}
  function addGate(x){const d=DIFFICULTIES[state.difficulty],gap=Math.max(d.gap-28,d.gap-state.score*1.1),center=175+gap/2+Math.random()*(groundY-210-gap);gates.push({x,w:70,gapTop:center-gap/2,gapBottom:center+gap/2,passed:false,star:Math.random()<.5,starTaken:false})}
  function input(){if(state.mode==='menu'||state.mode==='gameover')start();else if(state.mode==='playing')flap()}
  function burst(x,y,color,n=14){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*130;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.6+Math.random()*.35,c:color})}}
  function die(){if(state.mode!=='playing')return;state.mode='gameover';state.best=Math.max(state.best,state.score);localStorage.skyboundBest=state.best;tone(120,.28,'sawtooth',.05);burst(bird.x,bird.y,'#ff7a91',22)}
  function update(dt){state.time+=dt;clouds.forEach(c=>{c.x-=c.v*dt;if(c.x<-c.s*3)c.x=W+c.s*2});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(state.mode!=='playing')return;const d=DIFFICULTIES[state.difficulty];state.speed=Math.min(d.maxSpeed,d.speed+state.score*3);bird.vy+=980*dt;bird.y+=bird.vy*dt;bird.rot=Math.max(-.45,Math.min(1.15,bird.vy/500));gates.forEach(g=>g.x-=state.speed*dt);if(gates[0]&&gates[0].x+gates[0].w<-10){gates.shift();addGate(gates[gates.length-1].x+d.spacing)}for(const g of gates){if(!g.passed&&g.x+g.w<bird.x){g.passed=true;state.score++;tone(720,.07,'sine')}const sx=g.x+g.w/2,sy=(g.gapTop+g.gapBottom)/2;if(g.star&&!g.starTaken&&Math.hypot(bird.x-sx,bird.y-sy)<30){g.starTaken=true;state.stars++;tone(980,.12,'sine');burst(sx,sy,'#ffe56f')}if(bird.x+bird.r>g.x&&bird.x-bird.r<g.x+g.w&&(bird.y-bird.r<g.gapTop||bird.y+bird.r>g.gapBottom))die()}if(bird.y+bird.r>groundY||bird.y-bird.r<0)die()}
  function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
  function drawCloud(c){ctx.fillStyle='#ffffff20';ctx.beginPath();ctx.arc(c.x,c.y,c.s*.55,0,7);ctx.arc(c.x+c.s*.65,c.y-8,c.s*.75,0,7);ctx.arc(c.x+c.s*1.35,c.y,c.s*.5,0,7);ctx.fill()}
  function render(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#526ee8');sky.addColorStop(.55,'#d06ee0');sky.addColorStop(1,'#ffb56b');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffeaa944';ctx.beginPath();ctx.arc(380,160,78,0,7);ctx.fill();ctx.fillStyle='#fff0b6';ctx.beginPath();ctx.arc(380,160,47,0,7);ctx.fill();clouds.forEach(drawCloud);ctx.fillStyle='#6a4eb070';ctx.beginPath();ctx.moveTo(0,590);for(let x=0;x<=W;x+=60)ctx.lineTo(x,510+Math.sin(x*.035)*32);ctx.lineTo(W,groundY);ctx.lineTo(0,groundY);ctx.fill();for(const g of gates){const grad=ctx.createLinearGradient(g.x,0,g.x+g.w,0);grad.addColorStop(0,'#644be0');grad.addColorStop(.5,'#9c7cff');grad.addColorStop(1,'#4932b0');ctx.fillStyle=grad;ctx.shadowColor='#5b3ee8';ctx.shadowBlur=18;rr(g.x,-18,g.w,g.gapTop+18,18);rr(g.x,g.gapBottom,g.w,groundY-g.gapBottom+22,18);ctx.shadowBlur=0;ctx.fillStyle='#c3b5ff';rr(g.x-7,g.gapTop-22,g.w+14,22,9);rr(g.x-7,g.gapBottom,g.w+14,22,9);if(g.star&&!g.starTaken)drawStar(g.x+g.w/2,(g.gapTop+g.gapBottom)/2,11+Math.sin(state.time*5)*2)}ctx.fillStyle='#34265e';ctx.fillRect(0,groundY,W,H-groundY);ctx.fillStyle='#ffe06a';ctx.fillRect(0,groundY,W,7);particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*1.6);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,3.5,0,7);ctx.fill()});ctx.globalAlpha=1;drawBird();if(state.mode==='playing'){ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='700 56px Fredoka';ctx.shadowColor='#4a3579';ctx.shadowBlur=12;ctx.fillText(state.score,W/2,78);ctx.shadowBlur=0;ctx.textAlign='left';ctx.font='600 18px Fredoka';ctx.fillStyle='#fff8';ctx.fillText('★ '+state.stars,22,40);ctx.textAlign='center';ctx.font='600 13px Fredoka';ctx.fillStyle=DIFFICULTIES[state.difficulty].color;ctx.fillText(DIFFICULTIES[state.difficulty].label,W/2,101)}if(state.mode==='menu')difficultyMenu();if(state.mode==='paused')overlay('PAUSED','Take a breath up here.','TAP OR P TO RESUME');if(state.mode==='gameover')gameOver()}
  function drawStar(x,y,r){ctx.save();ctx.translate(x,y);ctx.rotate(state.time);ctx.fillStyle='#ffe66e';ctx.shadowColor='#fff3a0';ctx.shadowBlur=14;ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rad=i%2?r*.45:r;ctx.lineTo(Math.cos(a)*rad,Math.sin(a)*rad)}ctx.closePath();ctx.fill();ctx.restore()}
  function drawBird(){ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.rot);ctx.shadowColor='#552a74';ctx.shadowBlur=14;ctx.fillStyle='#ffea69';ctx.beginPath();ctx.ellipse(0,0,23,18,0,0,7);ctx.fill();ctx.fillStyle='#ff8b6b';ctx.beginPath();ctx.moveTo(17,-2);ctx.lineTo(36,4);ctx.lineTo(17,10);ctx.fill();ctx.fillStyle='#7853d8';ctx.beginPath();ctx.ellipse(-10,5,15,8,-.4,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(8,-7,7,0,7);ctx.fill();ctx.fillStyle='#23203c';ctx.beginPath();ctx.arc(11,-7,3,0,7);ctx.fill();ctx.restore()}
  function overlay(title,sub,cta){ctx.fillStyle='#1713329c';rr(48,210,384,270,28);ctx.textAlign='center';ctx.fillStyle='#ffe46e';ctx.font='700 48px Fredoka';ctx.fillText(title,W/2,292);ctx.fillStyle='#e6e8ff';ctx.font='500 18px Fredoka';ctx.fillText(sub,W/2,334);ctx.fillStyle='#ffffff24';rr(105,375,270,60,18);ctx.fillStyle='#fff';ctx.font='700 19px Fredoka';ctx.fillText(cta,W/2,413)}
  function difficultyMenu(){ctx.fillStyle='#171332ae';rr(34,168,412,350,28);ctx.textAlign='center';ctx.fillStyle='#ffe46e';ctx.font='700 45px Fredoka';ctx.fillText('SKYBOUND',W/2,237);ctx.fillStyle='#e6e8ff';ctx.font='500 17px Fredoka';ctx.fillText('CHOOSE YOUR FLIGHT',W/2,275);const modes=['chill','classic','turbo'];modes.forEach((key,i)=>{const d=DIFFICULTIES[key],x=48+i*132;ctx.fillStyle=d.color+'35';rr(x,315,120,108,18);ctx.strokeStyle=d.color;ctx.lineWidth=2;ctx.strokeRect(x+.5,315.5,119,107);ctx.fillStyle=d.color;ctx.font='700 18px Fredoka';ctx.fillText(d.label,x+60,351);ctx.fillStyle='#fff';ctx.font='500 13px Fredoka';ctx.fillText(key==='chill'?'WIDE + SLOW':key==='classic'?'BALANCED':'TIGHT + FAST',x+60,382);ctx.fillStyle='#ffffff88';ctx.font='500 12px Fredoka';ctx.fillText('KEY '+(i+1),x+60,405)});ctx.fillStyle='#c8c5e7';ctx.font='500 14px Fredoka';ctx.fillText('Tap a mode to start flying',W/2,470)}
  function gameOver(){ctx.fillStyle='#171332b8';rr(58,150,364,390,28);ctx.textAlign='center';ctx.fillStyle='#ff8e9f';ctx.font='700 43px Fredoka';ctx.fillText('FLIGHT OVER',W/2,218);ctx.fillStyle=DIFFICULTIES[state.difficulty].color;ctx.font='700 14px Fredoka';ctx.fillText(DIFFICULTIES[state.difficulty].label+' MODE',W/2,248);ctx.fillStyle='#fff';ctx.font='700 64px Fredoka';ctx.fillText(state.score,W/2,323);ctx.font='500 16px Fredoka';ctx.fillStyle='#cbc8e8';ctx.fillText('SCORE',W/2,349);ctx.font='600 18px Fredoka';ctx.fillText('BEST  '+state.best+'     ★  '+state.stars,W/2,393);ctx.fillStyle='#ffe46e';rr(110,424,260,58,18);ctx.fillStyle='#302653';ctx.font='700 19px Fredoka';ctx.fillText('FLY AGAIN',W/2,461);ctx.fillStyle='#ffffff20';rr(150,492,180,34,12);ctx.fillStyle='#e8e5ff';ctx.font='600 13px Fredoka';ctx.fillText('CHANGE MODE',W/2,514)}
  function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}
  canvas.addEventListener('pointerdown',e=>{const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*W/rect.width,y=(e.clientY-rect.top)*H/rect.height;if(state.mode==='menu'){if(y>=315&&y<=423){if(x>=48&&x<=168)start('chill');else if(x>=180&&x<=300)start('classic');else if(x>=312&&x<=432)start('turbo')}return}if(state.mode==='gameover'&&y>=485&&y<=540){state.mode='menu';return}input()});document.addEventListener('keydown',e=>{if(state.mode==='menu'&&['1','2','3'].includes(e.key)){start(['chill','classic','turbo'][+e.key-1]);return}if(e.key.toLowerCase()==='m'&&state.mode==='gameover'){state.mode='menu';return}if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();input()}if(e.key.toLowerCase()==='p'&&(state.mode==='playing'||state.mode==='paused'))state.mode=state.mode==='paused'?'playing':'paused';if(e.key.toLowerCase()==='f')document.fullscreenElement?document.exitFullscreen():canvas.parentElement.requestFullscreen();if(e.key==='Enter'&&state.mode==='gameover')start()});document.querySelector('#soundBtn').onclick=e=>{e.stopPropagation();state.muted=!state.muted;e.currentTarget.classList.toggle('muted',state.muted)};
  window.advanceTime=ms=>{for(let i=0;i<Math.max(1,Math.round(ms/(1000/60)));i++)update(1/60);render()};window.render_game_to_text=()=>JSON.stringify({coordinates:'origin top-left, x right, y down',mode:state.mode,difficulty:state.difficulty,difficultySettings:DIFFICULTIES[state.difficulty],player:{x:+bird.x.toFixed(1),y:+bird.y.toFixed(1),vy:+bird.vy.toFixed(1),radius:bird.r},visibleGates:gates.filter(g=>g.x<W).map(g=>({x:+g.x.toFixed(1),width:g.w,gapTop:+g.gapTop.toFixed(1),gapBottom:+g.gapBottom.toFixed(1),star:g.star&&!g.starTaken})),score:state.score,best:state.best,stars:state.stars,speed:+state.speed.toFixed(1)});render();requestAnimationFrame(loop);
})();
